apt:
  repositories:
    - sudo add-apt-repository multiverse
  base_packages:
    - curl openssl dkms git zsh
    - gcc make cmake build-essential 
    - adb usbmuxd dnsmasq bc 
    - libssl-dev libbz2-dev libsqlite3-dev liblzma-dev tk-dev zlib1g zlib1g-dev libbz2-dev libreadline-dev
    - snapd
  script_packages:
    - 'if [ ! -d ~/.oh-my-zsh ]; then yes "y" |  sh -c "$(curl -fsSL https://raw.github.com/ohmyzsh/ohmyzsh/master/tools/install.sh)"; fi' #oh-my-zsh
  packages:
    - fonts-firacode xclip fzf jq
    - gnome-terminal font-manager
